### ISSUE TITLE
u64 vs size_t -> std::min won't compile on clang

### ISSUE THREAD

**Issue by conradjones** [REDasmOrg/REDasm#14] opened 2019-02-26 17:07 UTC
I see various places mixing of types in std::min calls which fail to compile on clang 7.0 due to mismatched types, such as a call to std::min(size_t, u64) 

Quite happy to submit a PR, I'm having to modify it to get it to compile anyway. What was the reasoning behind the u64 type and not a builtin language type ?

**Comment by Dax89** [comment] 2019-02-26 18:45
Hi,

u64 is just a typedef of uint64_t, the reason is that the first one is shorter and faster to write than the second one.
I have several warnings about that even on msvc compiler (gcc doesn't complains), it need to check and removed all of it.

Feel free to send pull requests anyway!

**Comment by dgellow** [comment] 2019-03-05 10:26
We should be able to close this issue, build works fine now using clang.

**Closed** 2019-03-05 10:35 UTC

**Comment by danfe** [comment] 2019-05-12 16:21
The problem is a bit deeper, actually.  Version 2.1 builds fine on amd64 with Clang 8.0.0 but that's because `size_t` matches `u64` there.  Some methods return `size_t` and some `u64`, and when they're mixed together, like in those _min/max_ cases, the build fails on i386 (and probably any 32-bit arch) due to mismatches types (`size_t` is 4 bytes on i386).  I'll post a patch if I manage to fix it, for your consideration.

Version 2.0 builds fine on both i386 and amd64 (with couple of patches, but unrelated to this particular problem).
